/*
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a2 + b2 = c2
For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.
*/

#include <bits/stdc++.h>
using namespace std;

int main() {
  int ans;
  
  /*
  Primitive Pythagorean triples generated by
  a=m^2-n^2
  b=2mn
  c=m^2+n^2
  
  Scale appropriately
  */
    
  for(int m=1; m*m<500; m++){
  	for(int n=m+1; n*n<500; n++){
  	  if(1000%(2*n*n+2*m*n)==0){
  	  	ans=1;
  	  	ans*=n*n-m*m;
  	  	ans*=2*n*m;
  	  	ans*=n*n+m*m;
  	  	for(int z=0; z<3; z++){
  	  	  ans*=1000/(2*n*n+2*m*n);
  	  	}
  	  	break;
  	  }
  	}
  }
  
  cout << ans << endl;
}
